# Netlify配置文件
# 构建配置
[build]
  base = ""
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/build"
  functions = "netlify/functions"

# 环境变量
[build.environment]
  NODE_ENV = "production"
  CI = "false"

# 构建处理
[build.processing]
  skip_processing = false

# 函数配置
[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]

# 插件配置
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# API代理配置
[[redirects]]
  from = "/api/*"
  to = "https://aifae.netlify.app/api/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400"
    Vary = "Origin"

# 专门处理OPTIONS请求
[[redirects]]
  from = "/api/*"
  to = "https://aifae.netlify.app/api/:splat"
  status = 200
  force = true
  conditions = {Method = ["OPTIONS"]}
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400"
    Vary = "Origin"

# 静态资源重定向
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200

# 客户端路由重定向
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# 全局安全头
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self' https://aifae.netlify.app https://aifacetest11.netlify.app; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; connect-src 'self' https://aifacetest11.netlify.app;"

# API路径CORS配置
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://67ea87b0bacef7000851fdfa--aifae.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400"
    Vary = "Origin"

# 静态资源缓存配置
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/static/js/*"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/css/*"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, no-cache"
    Access-Control-Allow-Origin = "*" 