[build]
  base = ""
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "false"

[build.processing]
  skip_processing = true

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/static/js/*"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/static/css/*"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' *.netlify.app *.netlify.com; img-src 'self' data: blob: *.netlify.app *.netlify.com;"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 